export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const INCREMENT_OFFSET = 'INCREMENT_OFFSET';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
